cookie:
  expiry_days: 90
  key: some_random_secret_key
  name: recommender_cookie
credentials:
  usernames:
    hey:
      email: hey@gmail.com
      name: hey
      password: '$2b$12$31LOfVCiG/7dxWZ99bc1uuj9KJ.rawZt8xlDOS3EV/jKvItV.HUK2'
      user_id: 612
      role: 'user'
    user_1:
      email: user1@email.com
      name: User One(Admin)
      password: '$2b$12$pU.rsS9V1QRHU9lqa3n3Eepwe5MrfdQb7RAhwyZyviZ8gEMF71kNu'
      user_id: 1
      role: 'admin'
    user_267:
      email: user267@email.com
      name: User 267
      password: '$2b$12$pU.rsS9V1QRHU9lqa3n3Eepwe5MrfdQb7RAhwyZyviZ8gEMF71kNu'
      user_id: 267
      role: 'user'
    user_525:
      email: user525@email.com
      name: User 525
      password: '$2b$12$pU.rsS9V1QRHU9lqa3n3Eepwe5MrfdQb7RAhwyZyviZ8gEMF71kNu'
      user_id: 525
      role: 'user'
    user_91:
      email: user91@email.com
      name: User Ninety-One
      password: '$2b$12$pU.rsS9V1QRHU9lqa3n3Eepwe5MrfdQb7RAhwyZyviZ8gEMF71kNu'
      user_id: 91
      role: 'user'
